version: '3.5'

services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite:/data

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  azurite:
  